if(EXISTS "C:/Projects/Real-Roots-Polynomial-Engine/build2/UnitTesting/Test1[1]_tests.cmake")
  include("C:/Projects/Real-Roots-Polynomial-Engine/build2/UnitTesting/Test1[1]_tests.cmake")
else()
  add_test(Test1_NOT_BUILT Test1_NOT_BUILT)
endif()
